Update molo.core from 6.6.4 to 6.7.0
There are a number of migration issues that exist in molo.core, profiles and gem.
In order to avoid dependency issues with python3, we need to change which migrations depend on each other.

By changing the dependency from 0018_userprofile_admin_sites to 0019_add_uuid_field will avoid the following error:

Applying gem.0023_move_migrated_user_name_to_molo_profiles...Traceback (most recent call last):
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 385, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'User' object has no attribute '_profile_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: profiles_userprofile.uuid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/nathanbegbie/Repositories/molo-gem/gem/migrations/0023_move_migrated_user_name_to_molo_profiles.py", line 9, in switch_to_using_profiles_migrated_username
    call_command('copy_migrated_username_to_profile')
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/raven/contrib/django/management/__init__.py", line 37, in new_execute
    return original_func(self, *args, **kwargs)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/nathanbegbie/Repositories/molo-gem/gem/management/commands/copy_migrated_username_to_profile.py", line 11, in handle
    if hasattr(gem_profile.user, 'profile'):
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 393, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/nathanbegbie/.virtualenvs/gemPy3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: profiles_userprofile.uuid